#+title: Announcing the System Crafters Forum!
#+date: [2024-02-01 Thu]
#+author: David Wilson
#+kind: news

Today I'm excited to announce the launch of the new [[https://forum.systemcrafters.net][System Crafters Forum]]!

For years now, our community has lacked a good middle ground between the main System Crafters website and the various chat channels we've used (Discord, Matrix, IRC) to offer a more reliable environment for asking questions, finding answers, and sharing the cool things we've made.

I recently started looking into [[https://www.discourse.org][Discourse]] as an option and was very impressed with the capabilities that they provide.  I feel confident that our new forum be the ideal home for many of the community activities that I'm planning in the near future like hackathons, mini-conferences, courses, mentoring groups, and more!

With the introduction of the forum, the IRC chat will become more of a lounge for the community where people can hang out and discuss topics of interest in a more ephemeral way.  Any time a question in the chat is more deep than just a one-line answer, it should probably move to the forum so that others can find the answer in the future!

To start things off, I've added categories for relevant topics like [[https://forum.systemcrafters.net/c/emacs][Emacs]], [[https://forum.systemcrafters.net/c/guix][Guix]], and [[https://forum.systemcrafters.net/c/programming][Programming]], but there's probably a lot more we'd like to discuss.  Please [[https://forum.systemcrafters.net/new-topic?&category=General][create a post]] and suggest other categories we should add!

If you're interested to participate, head to the [[https://forum.systemcrafters.net/][forum site]], browse around, and then sign up for an account.  We look forward to seeing you there!
